export const CHANGE_COLOR = "CHANGE_COLOR";
export const UPDATE_TETRI = "UPDATE_TETRI";
export const TETRI_MOVE = "TETRI_MOVE";
export const UPDATE_INPUT_USERNAME = "UPDATE_INPUT_USERNAME";
export const UPDATE_USERNAME = "UPDATE_USERNAME";